### ISSUE TITLE
Undefined property: coordinates in GeometryProxy.php

### ISSUE THREAD

**Issue by pavloniym** [spinen/laravel-geometry#25] opened 2019-05-17 11:19 UTC
Thank you for your package.
I found an error connected with getSquareMeters() method in GeometryProxy class.

There is no **coordinates** property on class, so then i try to calculate area i will get an error.

 ```php
// GeometryProxy.php

/**
     * Calculate the square meters
     *
     * @return float
     */
    public function getSquareMeters()
    {
        if (!is_null($this->cached_area)) {
            return $this->cached_area;
        }

        $this->cached_area = 0.0;

        foreach ($this->coordinates as $coordinate) {
            $this->cached_area += $this->ringArea($coordinate);
        }

        return $this->cached_area;
    }
```

Package version: 2.0

**Comment by jimmypuckett** [comment] 2019-05-17 16:06
Can you show me how you are using it the class?

**Comment by pavloniym** [comment] 2019-05-17 16:44
Of course!
Maybe I misunderstand something...

- I resolve package using default Laravel resolve() function
- Pass WKT geometry from db to package's parseWkt() method and get GeometryCollection object
- Call getSquareMeters() method and get error

```php

public function getGeometryArea(string $coordinatesAsWkt): float
{
        $geometry = resolve(\Spinen\Geometry\Geometry::class);
        $collection = $geometry->parseWkt($coordinatesAsWkt);

        return $collection->getSquareMeteres()
}

```

Can't find any logic connected with **coordinates** property in GeometryProxy class ...
Please help!

**Comment by jimmypuckett** [comment] 2019-05-17 17:18
I am sorry that you are having issues.  We build these packages for our internal use & then put them out there without as much documentation as they really need.  The reason that you don't see a `coordinates` property, as it is hidden in the `__get`.  This `Proxy` class is a wrapper or proxy to the actual `geoPHP` class.  "automagically" gets the property from the root class.  Our proxy is just a way to ad some "sugar" to those classes.

Will you put a `dd($collection);` before your return & paste the response?

Can you post the `Wkt` that you are parsing?

I think that the collection maybe null & there for has no coordinates.  Then we have a bug in the code that should make sure that the object has coordinates before calculating area.

**Comment by pavloniym** [comment] 2019-05-17 18:41
Sure!


<details> 
  <summary>This is my geometry object after singleton resolution</summary>

```php
Geometry {#723
  #app: null
  #geoPhp: geoPHP {#722}
  #mapper: TypeMapper {#721
    #types: array:11 [
      "Ewkb" => "ewkb"
      "Ewkt" => "ewkt"
      "GeoHash" => "geohash"
      "GeoJson" => "geojson"
      "GeoRss" => "georss"
      "GoogleGeocode" => "google_geocode"
      "Gpx" => "gpx"
      "Json" => "json"
      "Kml" => "kml"
      "Wkb" => "wkb"
      "Wkt" => "wkt"
    ]
  }
}
```
</details>

<details> 
  <summary>This is my collection object </summary>

```php
GeometryCollection {#737
  #cached_area: null
  #geometry: GeometryCollection {#750
    #geom_type: "GeometryCollection"
    +components: array:3 [
      0 => Point {#741
        +coords: array:2 [
          0 => 102.0
          1 => 0.5
        ]
        #geom_type: "Point"
        #dimension: 2
        -geos: null
        #srid: null
      }
      1 => LineString {#739
        #geom_type: "LineString"
        +components: array:4 [
          0 => Point {#732
            +coords: array:2 [
              0 => 102.0
              1 => 0.0
            ]
            #geom_type: "Point"
            #dimension: 2
            -geos: null
            #srid: null
          }
          1 => Point {#698
            +coords: array:2 [
              0 => 103.0
              1 => 1.0
            ]
            #geom_type: "Point"
            #dimension: 2
            -geos: null
            #srid: null
          }
          2 => Point {#703
            +coords: array:2 [
              0 => 104.0
              1 => 0.0
            ]
            #geom_type: "Point"
            #dimension: 2
            -geos: null
            #srid: null
          }
          3 => Point {#710
            +coords: array:2 [
              0 => 105.0
              1 => 1.0
            ]
            #geom_type: "Point"
            #dimension: 2
            -geos: null
            #srid: null
          }
        ]
        -geos: null
        #srid: null
      }
      2 => Polygon {#749
        #geom_type: "Polygon"
        +components: array:1 [
          0 => LineString {#740
            #geom_type: "LineString"
            +components: array:5 [
              0 => Point {#727
                +coords: array:2 [
                  0 => 100.0
                  1 => 0.0
                ]
                #geom_type: "Point"
                #dimension: 2
                -geos: null
                #srid: null
              }
              1 => Point {#716
                +coords: array:2 [
                  0 => 101.0
                  1 => 0.0
                ]
                #geom_type: "Point"
                #dimension: 2
                -geos: null
                #srid: null
              }
              2 => Point {#726
                +coords: array:2 [
                  0 => 101.0
                  1 => 1.0
                ]
                #geom_type: "Point"
                #dimension: 2
                -geos: null
                #srid: null
              }
              3 => Point {#678
                +coords: array:2 [
                  0 => 100.0
                  1 => 1.0
                ]
                #geom_type: "Point"
                #dimension: 2
                -geos: null
                #srid: null
              }
              4 => Point {#734
                +coords: array:2 [
                  0 => 100.0
                  1 => 0.0
                ]
                #geom_type: "Point"
                #dimension: 2
                -geos: null
                #srid: null
              }
            ]
            -geos: null
            #srid: null
          }
        ]
        -geos: null
        #srid: null
      }
    ]
    -geos: null
    #srid: null
  }
  #geometry_array: null
  #mapper: TypeMapper {#721
    #types: array:11 [
      "Ewkb" => "ewkb"
      "Ewkt" => "ewkt"
      "GeoHash" => "geohash"
      "GeoJson" => "geojson"
      "GeoRss" => "georss"
      "GoogleGeocode" => "google_geocode"
      "Gpx" => "gpx"
      "Json" => "json"
      "Kml" => "kml"
      "Wkb" => "wkb"
      "Wkt" => "wkt"
    ]
  }
}
```
</details>

<details> 
  <summary>This is my WKT content</summary>
   
```php
GEOMETRYCOLLECTION(POINT(102 0.5),LINESTRING(102 0,103 1,104 0,105 1),POLYGON((100 0,101 0,101 1,100 1,100 0)))
```
</details>


<details> 
  <summary>Error for getSquareMeters()</summary>

```php
RuntimeException {#756
  #message: "Undefined property: coordinates"
  #code: 0
  #file: "/my-project/vendor/spinen/laravel-geometry/src/Support/GeometryProxy.php"
  #line: 120
  trace: {
    /my-project/vendor/spinen/laravel-geometry/src/Support/GeometryProxy.php:120 {}
    /my-project/vendor/spinen/laravel-geometry/src/Support/GeometryProxy.php:204 {}
    /my-project/app/my-project/Cartography/Models/Objects/ObjectsGeometry.php:41 {
      › dump('area next');
      › dump($model->geometry->parseWkt($model->coordinatesAsWkt)->getSquareMeters());
      › 
    }
    /my-project/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:347 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:196 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:188 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:704 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:675 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Support/HigherOrderTapProxy.php:34 {}
    /my-project/nova/src/Http/Controllers/ResourceUpdateController.php:36 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:348 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:237 {}
    /my-project/nova/src/Http/Controllers/ResourceUpdateController.php:41 {}
    Laravel\Nova\Http\Controllers\ResourceUpdateController->handle() {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php:680 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30 {}
    /my-project/nova/src/Http/Middleware/Authorize.php:18 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/nova/src/Http/Middleware/BootTools.php:20 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/nova/src/Http/Middleware/DispatchServingNovaEvent.php:20 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43 {}
    /my-project/nova/src/Http/Middleware/Authenticate.php:31 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:75 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:56 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php:682 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php:657 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php:623 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Router.php:612 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30 {}
    /my-project/nova/src/Http/Middleware/ServeNova.php:26 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/fideloper/proxy/src/TrustProxies.php:57 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151 {}
    /my-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116 {}
    /my-project/public/index.php:55 {}
  }
}

```
</details>

Thank you for such quick response!
Hope it helps to understand and resolve this issue

P.S.
I tried many different geometry collections - with single feature, with polygons (with & without holes), etc - no success ...
Another functionality (converting to formats and geoPHP methods) works perfect

**Comment by jimmypuckett** [comment] 2019-05-17 19:53
OK, The problem is that you are passing in a collection of geometries & our code is not smart enough to deal with that situation.  The `wkt` that you are working with is actually 3 geometries... a point, a line, & a polygon.  Therefore, our code is trying to calculate the area of a collection.  If you use just the polygon, then it works (I am doing this in raw php as I don't have a Laravel project with the package installed on my machine)...

```php
:) psysh
Psy Shell v0.5.2 (PHP 7.2.17 — cli) by Justin Hileman
>>> $geo = new geoPHP();
=> geoPHP {#164}
>>> $mapper = new Spinen\Geometry\Support\TypeMapper();
=> Spinen\Geometry\Support\TypeMapper {#163}
>>> $geometry = new Spinen\Geometry\Geometry($geo, $mapper);
=> Spinen\Geometry\Geometry {#170}
>>> $collection = $geometry->parseWkt('POLYGON((100 0,101 0,101 1,100 1,100 0))')
=> Spinen\Geometry\Geometries\Polygon {#157}
>>> $collection->getSquareMeters()
=> -12391399902.071
>>>
```

The code works with the `linestring`...

```php
>>> $collection = $geometry->parseWkt('LINESTRING(102 0,103 1,104 0,105 1)')
=> Spinen\Geometry\Geometries\LineString {#180}
>>> $collection->getSquareMeters()
=> 0.0
```

but there is an error with the `point`...

```php
>>> $collection = $geometry->parseWkt('POINT(102 0.5)')
=> Spinen\Geometry\Geometries\Point {#160}
>>> $collection->getSquareMeters()
PHP warning:  count(): Parameter must be an array or an object that implements Countable in ~/git/_libraries/laravel-geometry/src/Support/GeometryProxy.php on line 244
```

I am going to close this issue as it is rally about `GEOMETRYCOLLECTION` & we will address it some day if it becomes important a requirement.  Also, I am not sure of the expected behavior...

* Should it add the area of all of the items in the collection?
* Should it give an array areas for each item?
* Should it give an error?

Really, we need to spend some time to write some docs.

I hope that this is helpful & that you don't feel that we are brushing off the issue.  If you have a good suggestion about how you would like to see the `GEOMETRYCOLLECTION`'s handled, then please let us know & se can see about getting it worked in.

**Closed as completed by jimmypuckett** 2019-05-17 19:53 UTC

**Comment by pavloniym** [comment] 2019-05-17 20:04
Ok, thanks!
